export const Colors = {
  dark: {
    bg: '#0f0f0f',
    bgSecondary: '#1a1a1a',
    bgTertiary: '#272727',
    surface: '#1f1f1f',
    border: '#2a2a2a',
    borderLight: '#1f1f1f',
    text: '#f1f1f1',
    textSecondary: '#aaaaaa',
    textMuted: '#606060',
    accent: '#ff0000',
    accentFg: '#ffffff',
    iconActive: '#ffffff',
    iconInactive: '#909090',
    chip: '#272727',
    chipText: '#f1f1f1',
    chipActive: '#f1f1f1',
    chipActiveText: '#0f0f0f',
    inputBg: '#1a1a1a',
    inputBorder: '#2a2a2a',
    inputText: '#f1f1f1',
    inputPlaceholder: '#555',
    cardBg: 'transparent',
    thumbBg: '#1c1c1c',
    skeleton: '#272727',
    overlay: 'rgba(0,0,0,0.7)',
    tabBar: '#0f0f0f',
    tabBarBorder: '#1f1f1f',
    google: '#ffffff',
    googleText: '#0f0f0f',
  },
  light: {
    bg: '#ffffff',
    bgSecondary: '#f8f8f8',
    bgTertiary: '#f2f2f2',
    surface: '#ffffff',
    border: '#e8e8e8',
    borderLight: '#f0f0f0',
    text: '#0f0f0f',
    textSecondary: '#606060',
    textMuted: '#aaaaaa',
    accent: '#ff0000',
    accentFg: '#ffffff',
    iconActive: '#0f0f0f',
    iconInactive: '#909090',
    chip: '#f0f0f0',
    chipText: '#0f0f0f',
    chipActive: '#0f0f0f',
    chipActiveText: '#ffffff',
    inputBg: '#f5f5f5',
    inputBorder: '#e8e8e8',
    inputText: '#0f0f0f',
    inputPlaceholder: '#aaa',
    cardBg: 'transparent',
    thumbBg: '#f0f0f0',
    skeleton: '#e8e8e8',
    overlay: 'rgba(0,0,0,0.5)',
    tabBar: '#ffffff',
    tabBarBorder: '#e8e8e8',
    google: '#ffffff',
    googleText: '#0f0f0f',
  },
} as const

export type ThemeColors = typeof Colors.dark
export type ThemeMode = 'dark' | 'light'
